version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    env_file:
      - ./includes/.env
      
    environment:
      - MYSQL_HOST=db  # Opcional, para sobreescribir el valor del archivo .env si lo necesitas en Docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=bienesraices_crud

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bienesraices_crud
    volumes:
      - db_data:/var/lib/mysql
      - ./includes/bienesraices_crud.sql:/docker-entrypoint-initdb.d/bienesraices_crud.sql

volumes:
  db_data:
