[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "apache2-foreground"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
internal_port = 80
protocol = "tcp"

[database]
engine = "mysql"
version = "5.7"