services:
  - type: web
    name: php-mvc-app
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: dpg-your-db-host
      - key: DB_USER
        value: your_db_user
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: bienesraices_crud
      - key: EMAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: EMAIL_PORT
        value: 2525
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    disk:
      name: web-data
      mountPath: /var/www/storage
      sizeGB: 1

databases:
  - name: bienesraices-db
    plan: starter
    databaseName: bienesraices_crud
    ipAllowList: []