services:
  - type: web
    name: bienes-raices-mvc
    env: docker
    plan: starter
    region: ohio
    buildCommand: docker build -t bienes-raices-mvc .
    startCommand: docker run -p 80:80 bienes-raices-mvc
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: bienes-raices-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: bienes-raices-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: bienes-raices-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: bienes-raices-db
          property: database
      - key: EMAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: EMAIL_PORT
        value: 2525
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: bienes-raices-db
    plan: starter
    databaseName: bienesraices_crud
    ipAllowList: []